title: overheidnl.github.io

include: [README.md,CONTRIBUTING.md,GOVERNANCE.md]
permalink: pretty

toc: true

# Page defaults in order to put the right design with the right class of page
defaults:
  -
    scope:
      path: "organisations/index.md"
    values:
      layout: "organisations"
  -
    scope:
      path: "organisations/*/index.md"
    values:
      layout: "organisation"
  -
    scope:
      path: "organisations/*/*"
    values:
      layout: "api"

# Use the amsterdam-jekyll-theme from https://github.com/Amsterdam/amsterdam-jekyll-theme
remote_theme: overheidnl/jekyll-overheidnl-theme
headerHideLogo: true
